package com.wms.controller;

import com.wms.entity.Portfolio;
import com.wms.entity.Report;
import com.wms.entity.Report.ReportType;
import com.wms.service.PortfolioService;
import com.wms.service.ReportService;
import com.wms.service.UserService;
import jakarta.validation.Valid;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import java.util.List;

/**
 * ========================================
 * REPORT CONTROLLER
 * ========================================
 */
@Controller
@RequestMapping("/reports")
public class ReportController {
    
    private final ReportService reportService;
    private final PortfolioService portfolioService;
    private final UserService userService;
    
    public ReportController(ReportService reportService, 
                           PortfolioService portfolioService,
                           UserService userService) {
        this.reportService = reportService;
        this.portfolioService = portfolioService;
        this.userService = userService;
    }
    
    // ========================================
    // LIST OPERATIONS
    // ========================================
    
    /**
     * LIST ALL REPORTS
     * ----------------
     */
    @GetMapping
    public String listReports(Model model) {
        List<Report> reports = reportService.getAllReports();
        model.addAttribute("reports", reports);
        model.addAttribute("reportTypes", ReportType.values());
        model.addAttribute("userNames", getUserNamesMap(reports));
        return "report/list";
    }
    
    /**
     * LIST REPORTS BY TYPE
     * --------------------
     */
    @GetMapping("/type/{type}")
    public String listReportsByType(@PathVariable("type") ReportType type, Model model) {
        List<Report> reports = reportService.getReportsByType(type);
        model.addAttribute("reports", reports);
        model.addAttribute("userNames", getUserNamesMap(reports));
        model.addAttribute("selectedType", type);
        model.addAttribute("reportTypes", ReportType.values());
        return "report/list";
    }
    
    /**
     * LIST PORTFOLIO REPORTS
     * ----------------------
     */
    @GetMapping("/portfolio/{portfolioId}")
    public String listPortfolioReports(@PathVariable("portfolioId") Long portfolioId, Model model) {
        Portfolio portfolio = portfolioService.getPortfolioById(portfolioId)
                .orElseThrow(() -> new RuntimeException("Portfolio not found"));
        
        List<Report> reports = reportService.getPortfolioReports(portfolioId);
        
        model.addAttribute("portfolio", portfolio);
        model.addAttribute("reports", reports);
        model.addAttribute("userNames", getUserNamesMap(reports));
        return "report/portfolio-reports";
    }
    
    /**
     * LIST CLIENT REPORTS
     * -------------------
     */
    @GetMapping("/client/{clientId}")
    public String listClientReports(@PathVariable("clientId") Long clientId, Model model) {
        List<Report> reports = reportService.getClientReports(clientId);
        model.addAttribute("reports", reports);
        model.addAttribute("clientId", clientId);
        model.addAttribute("userNames", getUserNamesMap(reports));
        return "report/list";
    }
    
    // ========================================
    // VIEW OPERATIONS
    // ========================================
    
    /**
     * VIEW REPORT
     * -----------
     */
    @GetMapping("/{id}")
    public String viewReport(@PathVariable("id") Long id, Model model) {
        Report report = reportService.getReportById(id)
                .orElseThrow(() -> new RuntimeException("Report not found with ID: " + id));
        
        model.addAttribute("report", report);
        
        // Add generated by username if available
        if (report.getGeneratedBy() != null) {
            userService.getUserById(report.getGeneratedBy())
                .ifPresent(user -> model.addAttribute("generatedByUsername", user.getUsername()));
        }
        
        // Parse allocation summary into structured list for display
        // Format: "VTI (Total Stock Market): ₹21,800 (40%)"
        if (report.getPortfolio() != null && report.getPortfolio().getAllocationSummary() != null 
                && !report.getPortfolio().getAllocationSummary().trim().isEmpty()) {
            String allocationSummary = report.getPortfolio().getAllocationSummary();
            java.util.List<java.util.Map<String, String>> allocations = new java.util.ArrayList<>();
            String[] lines = allocationSummary.split("\\r?\\n");
            for (String line : lines) {
                if (line != null && line.contains(":") && line.contains("₹")) {
                    java.util.Map<String, String> item = new java.util.HashMap<>();
                    
                    // Asset name is before the colon
                    item.put("asset", line.substring(0, line.indexOf(":")).trim());
                    
                    // Get the part after the colon: " ₹21,800 (40%)"
                    String afterColon = line.substring(line.indexOf(":") + 1).trim();
                    
                    // Extract value - from ₹ to the last ( which indicates percentage
                    String value = "-";
                    String pct = "-";
                    int rupeeIdx = afterColon.indexOf("₹");
                    int lastParenIdx = afterColon.lastIndexOf("(");
                    
                    if (rupeeIdx >= 0 && lastParenIdx > rupeeIdx) {
                        value = afterColon.substring(rupeeIdx, lastParenIdx).trim();
                    }
                    
                    // Extract percentage - between last ( and )
                    int lastCloseParenIdx = afterColon.lastIndexOf(")");
                    if (lastParenIdx >= 0 && lastCloseParenIdx > lastParenIdx) {
                        pct = afterColon.substring(lastParenIdx + 1, lastCloseParenIdx);
                    }
                    
                    item.put("value", value);
                    item.put("percentage", pct);
                    
                    allocations.add(item);
                }
            }
            model.addAttribute("allocations", allocations);
            
            // Always pass raw allocation summary for fallback display
            model.addAttribute("rawAllocationSummary", allocationSummary);
        }
        
        return "report/view";
    }
    
    // ========================================
    // GENERATE OPERATIONS
    // ========================================
    
    /**
     * SHOW GENERATE FORM (via /new path)
     * ----------------------------------
     */
    @GetMapping("/new")
    public String showNewForm(
            @RequestParam(value = "portfolioId", required = false) Long portfolioId,
            Model model) {
        return showGenerateForm(portfolioId, model);
    }
    
    /**
     * SHOW GENERATE FORM
     * ------------------
     */
    @GetMapping("/generate")
    public String showGenerateForm(
            @RequestParam(value = "portfolioId", required = false) Long portfolioId,
            Model model) {
        
        Report report = new Report();
        
        if (portfolioId != null) {
            Portfolio portfolio = portfolioService.getPortfolioById(portfolioId).orElse(null);
            report.setPortfolio(portfolio);
            model.addAttribute("selectedPortfolioId", portfolioId);
        }
        
        model.addAttribute("report", report);
        model.addAttribute("portfolios", portfolioService.getAllPortfolios());
        model.addAttribute("reportTypes", ReportType.values());
        return "report/form";
    }
    
    /**
     * CREATE REPORT (POST to /reports)
     * ---------------------------------
     */
    @PostMapping
    public String createReport(
            @Valid @ModelAttribute("report") Report report,
            BindingResult bindingResult,
            @RequestParam("portfolioId") Long portfolioId,
            Authentication authentication,
            RedirectAttributes redirectAttributes,
            Model model) {
        return generateReport(report, bindingResult, portfolioId, authentication, redirectAttributes, model);
    }
    
    /**
     * GENERATE REPORT
     * ---------------
     */
    @PostMapping("/generate")
    public String generateReport(
            @Valid @ModelAttribute("report") Report report,
            BindingResult bindingResult,
            @RequestParam("portfolioId") Long portfolioId,
            Authentication authentication,
            RedirectAttributes redirectAttributes,
            Model model) {
        
        if (bindingResult.hasErrors()) {
            model.addAttribute("portfolios", portfolioService.getAllPortfolios());
            model.addAttribute("reportTypes", ReportType.values());
            return "report/form";
        }
        
        try {
            // Set the generatedBy field from authenticated user
            if (authentication != null) {
                userService.getUserByUsername(authentication.getName())
                    .ifPresent(user -> report.setGeneratedBy(user.getUserId()));
            }
            
            Report saved = reportService.generateReport(portfolioId, report);
            redirectAttributes.addFlashAttribute("success", "Report generated successfully!");
            return "redirect:/reports/" + saved.getReportId();
            
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("error", e.getMessage());
            return "redirect:/reports/generate?portfolioId=" + portfolioId;
        }
    }
    
    /**
     * QUICK GENERATE
     * --------------
     * Generate a report with minimal input.
     */
    @PostMapping("/quick-generate")
    public String quickGenerate(
            @RequestParam("portfolioId") Long portfolioId,
            @RequestParam("reportType") ReportType reportType,
            Authentication authentication,
            RedirectAttributes redirectAttributes) {
        
        try {
            // Get user ID (simplified - in real app, get from UserService)
            Long userId = 1L; // Placeholder
            
            Report report = reportService.generateQuickReport(portfolioId, reportType, userId);
            redirectAttributes.addFlashAttribute("success", "Report generated successfully!");
            return "redirect:/reports/" + report.getReportId();
            
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("error", e.getMessage());
            return "redirect:/portfolios/" + portfolioId;
        }
    }
    
    // ========================================
    // UPDATE OPERATIONS
    // ========================================
    
    /**
     * ADD NOTES
     * ---------
     */
    @PostMapping("/{id}/notes")
    public String addNotes(
            @PathVariable("id") Long id,
            @RequestParam("notes") String notes,
            RedirectAttributes redirectAttributes) {
        
        try {
            reportService.addNotesToReport(id, notes);
            redirectAttributes.addFlashAttribute("success", "Notes added successfully!");
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("error", e.getMessage());
        }
        return "redirect:/reports/" + id;
    }
    
    // ========================================
    // DELETE OPERATIONS
    // ========================================
    
    @PostMapping("/{id}/delete")
    public String deleteReport(@PathVariable("id") Long id, RedirectAttributes redirectAttributes) {
        try {
            reportService.deleteReport(id);
            redirectAttributes.addFlashAttribute("success", "Report deleted successfully!");
        } catch (Exception e) {
            redirectAttributes.addFlashAttribute("error", e.getMessage());
        }
        return "redirect:/reports";
    }
    
    // ========================================
    // DOWNLOAD (PLACEHOLDER)
    // ========================================
    
    /**
     * DOWNLOAD REPORT
     * ---------------
     * Note: In a real application, this would generate a PDF.
     */
    @GetMapping("/{id}/download")
    public String downloadReport(@PathVariable("id") Long id, RedirectAttributes redirectAttributes) {
        // Placeholder - in real app, generate PDF and return as download
        redirectAttributes.addFlashAttribute("info", 
            "PDF download feature coming soon! Please use the print function.");
        return "redirect:/reports/" + id;
    }
    
    // ========================================
    // HELPER METHODS
    // ========================================
    
    /**
     * GET USER NAMES MAP
     * ------------------
     * Creates a map of user IDs to usernames for display in templates.
     */
    private java.util.Map<Long, String> getUserNamesMap(List<Report> reports) {
        java.util.Map<Long, String> userNames = new java.util.HashMap<>();
        for (Report report : reports) {
            if (report.getGeneratedBy() != null && !userNames.containsKey(report.getGeneratedBy())) {
                userService.getUserById(report.getGeneratedBy())
                    .ifPresent(user -> userNames.put(report.getGeneratedBy(), user.getFullName() != null ? user.getFullName() : user.getUsername()));
            }
        }
        return userNames;
    }
}
