package com.wms.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDate;

/**
 * ========================================
 * REPORT ENTITY
 * ========================================

 */
@Entity
@Table(name = "report")
public class Report {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long reportId;
    
    /**
     * RELATIONSHIP TO PORTFOLIO
     * -------------------------
     * Each report is generated for a specific portfolio.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "portfolio_id", nullable = false)
    private Portfolio portfolio;
    
    /**
     * REPORT DATE
     * -----------
     * When the report was generated.
     */
    @NotNull(message = "Report date is required")
    @Column(nullable = false)
    private LocalDate reportDate;
    
    /**
     * REPORT TYPE
     * -----------
     * What kind of report this is.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReportType reportType;
    
    /**
     * PERFORMANCE SUMMARY
     * -------------------
     * JSON containing performance metrics.
     */
    @Column(columnDefinition = "TEXT")
    private String performanceSummary;
    
    /**
     * REPORT TITLE
     * ------------
     * A descriptive title for the report.
     */
    @NotBlank(message = "Report title is required")
    @Size(max = 200)
    @Column(nullable = false, length = 200)
    private String reportTitle;
    
    /**
     * REPORT NOTES
     * ------------
     * Additional notes or recommendations from the financial advisor.
     */
    @Column(columnDefinition = "TEXT")
    private String notes;
    
    /**
     * GENERATED BY
     * ------------
     * User ID of the person who generated the report.
     */
    @Column(name = "generated_by")
    private Long generatedBy;
    
    // ========================================
    // ENUM
    // ========================================
    
    public enum ReportType {
        MONTHLY,
        QUARTERLY,
        ANNUAL,
        CUSTOM,
        PERFORMANCE,
        TAX
    }
    
    // ========================================
    // CONSTRUCTORS
    // ========================================
    
    public Report() {
        this.reportDate = LocalDate.now();
    }
    
    public Report(Portfolio portfolio, String reportTitle, ReportType reportType) {
        this.portfolio = portfolio;
        this.reportTitle = reportTitle;
        this.reportType = reportType;
        this.reportDate = LocalDate.now();
    }
    
    // ========================================
    // GETTERS AND SETTERS
    // ========================================
    
    public Long getReportId() {
        return reportId;
    }
    
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }
    
    public Portfolio getPortfolio() {
        return portfolio;
    }
    
    public void setPortfolio(Portfolio portfolio) {
        this.portfolio = portfolio;
    }
    
    public LocalDate getReportDate() {
        return reportDate;
    }
    
    public void setReportDate(LocalDate reportDate) {
        this.reportDate = reportDate;
    }
    
    public ReportType getReportType() {
        return reportType;
    }
    
    public void setReportType(ReportType reportType) {
        this.reportType = reportType;
    }
    
    public String getPerformanceSummary() {
        return performanceSummary;
    }
    
    public void setPerformanceSummary(String performanceSummary) {
        this.performanceSummary = performanceSummary;
    }
    
    public String getReportTitle() {
        return reportTitle;
    }
    
    public void setReportTitle(String reportTitle) {
        this.reportTitle = reportTitle;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public Long getGeneratedBy() {
        return generatedBy;
    }
    
    public void setGeneratedBy(Long generatedBy) {
        this.generatedBy = generatedBy;
    }
    
    @Override
    public String toString() {
        return "Report{" +
                "reportId=" + reportId +
                ", reportDate=" + reportDate +
                ", reportType=" + reportType +
                ", reportTitle='" + reportTitle + '\'' +
                '}';
    }
}
