package com.wms.repository;

import com.wms.entity.Report;
import com.wms.entity.Report.ReportType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

/**
 * ========================================
 * REPORT REPOSITORY
 * ========================================
 * 
 */
@Repository
public interface ReportRepository extends JpaRepository<Report, Long> {
    
    /**
     * FIND REPORTS BY PORTFOLIO
     * -------------------------
     */
    List<Report> findByPortfolioPortfolioId(Long portfolioId);
    
    /**
     * FIND REPORTS BY TYPE
     * --------------------
     */
    List<Report> findByReportType(ReportType reportType);
    
    /**
     * FIND REPORTS BY DATE RANGE
     * --------------------------
     */
    List<Report> findByReportDateBetween(LocalDate startDate, LocalDate endDate);
    
    /**
     * FIND REPORTS FOR A PORTFOLIO IN DATE RANGE
     * ------------------------------------------
     */
    List<Report> findByPortfolioPortfolioIdAndReportDateBetween(
            Long portfolioId, LocalDate startDate, LocalDate endDate);
    
    /**
     * FIND RECENT REPORTS
     * -------------------
     * 'After' = WHERE date > value
     */
    List<Report> findByReportDateAfter(LocalDate date);
    
    /**
     * FIND REPORTS GENERATED BY USER
     * ------------------------------
     */
    List<Report> findByGeneratedBy(Long userId);
    
    /**
     * COUNT REPORTS BY TYPE
     * ---------------------
     */
    long countByReportType(ReportType reportType);
    
    /**
     * FIND LATEST REPORT FOR PORTFOLIO
     * --------------------------------
     * Custom query to get the most recent report.
     */
    @Query("SELECT r FROM Report r WHERE r.portfolio.portfolioId = :portfolioId ORDER BY r.reportDate DESC LIMIT 1")
    Report findLatestReportForPortfolio(@Param("portfolioId") Long portfolioId);
    
    /**
     * FIND REPORTS BY CLIENT
     * ----------------------
     * Gets all reports for all portfolios belonging to a client.
     */
    @Query("SELECT r FROM Report r WHERE r.portfolio.client.clientId = :clientId ORDER BY r.reportDate DESC")
    List<Report> findReportsByClientId(@Param("clientId") Long clientId);
    
    /**
     * COUNT REPORTS FOR PORTFOLIO
     * ---------------------------
     */
    long countByPortfolioPortfolioId(Long portfolioId);
    
    /**
     * FIND BY TITLE CONTAINING
     * ------------------------
     */
    List<Report> findByReportTitleContainingIgnoreCase(String keyword);
    
    /**
     * FIND ALL ORDERED BY DATE
     * ------------------------
     */
    List<Report> findAllByOrderByReportDateDesc();
}
